name: ci-pr

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 构建文档
    uses: ./.github/workflows/build.yml

  upload:
    name: 请求部署预览
    runs-on: ubuntu-latest
    if: always() && github.repository == 'zotero-chinese/wiki' && github.event_name == 'pull_request'
    needs:
      - build
    steps:
      - name: 保存 PR 编号
        run: |
          echo "${{ github.event.number }}" > pr_num
      - name: 上传 PR 编号
        uses: actions/upload-artifact@v4
        with:
          name: pr-num
          path: ./pr_num
